#!/usr/bin/env bash
# Publishes a VERIFIED release artifact to the `release` branch (TASK-FND-016).
#
# The branch holds exactly the artifact tree (production Composer dependencies,
# compiled assets, deploy/ scripts, no secrets), one commit per release. The
# shared host is a Git clone of this branch and updates it with
# deploy/host-release.sh, so it needs neither Composer nor Node.
#
#   scripts/release/publish-release-branch.sh build/release/innsync-<version>-<commit>.zip
#
# Environment: REMOTE (default: origin; a name or a URL), BRANCH (default: release),
#              DRY_RUN=1 to build the commit without pushing.
set -euo pipefail

ZIP="${1:?usage: publish-release-branch.sh <artifact.zip>}"
[[ -f "$ZIP" ]] || { echo "not found: $ZIP" >&2; exit 1; }
ZIP="$(cd "$(dirname "$ZIP")" && pwd)/$(basename "$ZIP")"

REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
REMOTE="${REMOTE:-origin}"
BRANCH="${BRANCH:-release}"
REMOTE_URL="$(git -C "$REPO_ROOT" remote get-url "$REMOTE" 2>/dev/null || echo "$REMOTE")"

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

unzip -q "$ZIP" -d "$WORK/unpacked"
TREE="$(find "$WORK/unpacked" -mindepth 1 -maxdepth 1 -type d | head -n1)"
[[ -f "$TREE/RELEASE-MANIFEST.json" && -f "$TREE/deploy/host-release.sh" ]] || { echo "This is not a release artifact (manifest or deploy scripts missing)." >&2; exit 1; }
[[ ! -e "$TREE/.env" ]] || { echo "Refusing to publish an artifact that contains .env." >&2; exit 1; }

VERSION="$(sed -n 's/.*"version": "\(.*\)".*/\1/p' "$TREE/RELEASE-MANIFEST.json")"
COMMIT="$(sed -n 's/.*"commit": "\(.*\)".*/\1/p' "$TREE/RELEASE-MANIFEST.json")"
[[ -n "$VERSION" && -n "$COMMIT" ]] || { echo "Manifest lacks version or commit." >&2; exit 1; }
SHORT="${COMMIT:0:12}"

GIT=(git -c user.name="InnSYnc release" -c user.email="release@innsync.invalid" -c core.autocrlf=false)
CLONE="$WORK/branch"

if git ls-remote --exit-code --heads "$REMOTE_URL" "$BRANCH" >/dev/null 2>&1; then
    "${GIT[@]}" clone --quiet --branch "$BRANCH" --single-branch "$REMOTE_URL" "$CLONE"
    "${GIT[@]}" -C "$CLONE" rm -r -q --ignore-unmatch . >/dev/null
    find "$CLONE" -mindepth 1 -maxdepth 1 ! -name .git -exec rm -rf {} +
else
    mkdir -p "$CLONE"
    "${GIT[@]}" -C "$CLONE" init --quiet -b "$BRANCH"
fi

cp -a "$TREE"/. "$CLONE"/
"${GIT[@]}" -C "$CLONE" add -A -f

if "${GIT[@]}" -C "$CLONE" diff --cached --quiet && "${GIT[@]}" -C "$CLONE" rev-parse --verify --quiet HEAD >/dev/null; then
    echo "The release branch already holds this exact tree; nothing to publish."
    exit 0
fi

"${GIT[@]}" -C "$CLONE" commit --quiet -m "Release $VERSION ($SHORT)" -m "Built from $COMMIT. Do not edit: this branch is generated by scripts/release/publish-release-branch.sh."
TAG="release-$VERSION-$SHORT"
"${GIT[@]}" -C "$CLONE" tag -f "$TAG" >/dev/null

if [[ -n "${DRY_RUN:-}" ]]; then
    echo "Dry run: commit $(git -C "$CLONE" rev-parse --short HEAD) and tag $TAG created locally, not pushed."
    exit 0
fi

"${GIT[@]}" -C "$CLONE" push --quiet "$REMOTE_URL" "HEAD:refs/heads/$BRANCH" "refs/tags/$TAG"
echo "Published $TAG to $REMOTE_URL ($BRANCH)."
